register_event:
  target:
    entity:
      integration: steamvr
      domain: binary_sensor
      device_class: running
  fields:
    event:
      required: true
      example: "vr-event-button-press"
      selector:
        select:
          translation_key: "event"
          options:
            - "vr-event-none"
            - "vr-event-tracked-device-activated"
            - "vr-event-tracked-device-deactivated"
            - "vr-event-tracked-device-updated"
            - "vr-event-tracked-device-user-interaction-started"
            - "vr-event-tracked-device-user-interaction-ended"
            - "vr-event-ipd-changed"
            - "vr-event-enter-standby-mode"
            - "vr-event-leave-standby-mode"
            - "vr-event-tracked-device-role-changed"
            - "vr-event-watchdog-wake-up-requested"
            - "vr-event-lens-distortion-changed"
            - "vr-event-property-changed"
            - "vr-event-wireless-disconnect"
            - "vr-event-wireless-reconnect"
            - "vr-event-reserved-01"
            - "vr-event-reserved-02"
            - "vr-event-button-press"
            - "vr-event-button-unpress"
            - "vr-event-button-touch"
            - "vr-event-button-untouch"
            - "vr-event-modal-cancel"
            - "vr-event-mouse-move"
            - "vr-event-mouse-button-down"
            - "vr-event-mouse-button-up"
            - "vr-event-focus-enter"
            - "vr-event-focus-leave"
            - "vr-event-scroll-discrete"
            - "vr-event-touch-pad-move"
            - "vr-event-overlay-focus-changed"
            - "vr-event-reload-overlays"
            - "vr-event-scroll-smooth"
            - "vr-event-lock-mouse-position"
            - "vr-event-unlock-mouse-position"
            - "vr-event-input-focus-captured"
            - "vr-event-input-focus-released"
            - "vr-event-scene-application-changed"
            - "vr-event-input-focus-changed"
            - "vr-event-scene-application-using-wrong-graphics-adapter"
            - "vr-event-action-binding-reloaded"
            - "vr-event-hide-render-models"
            - "vr-event-show-render-models"
            - "vr-event-scene-application-state-changed"
            - "vr-event-scene-app-pipe-disconnected"
            - "vr-event-console-opened"
            - "vr-event-console-closed"
            - "vr-event-overlay-shown"
            - "vr-event-overlay-hidden"
            - "vr-event-dashboard-activated"
            - "vr-event-dashboard-deactivated"
            - "vr-event-dashboard-requested"
            - "vr-event-reset-dashboard"
            - "vr-event-image-loaded"
            - "vr-event-show-keyboard"
            - "vr-event-hide-keyboard"
            - "vr-event-overlay-gamepad-focus-gained"
            - "vr-event-overlay-gamepad-focus-lost"
            - "vr-event-overlay-shared-texture-changed"
            - "vr-event-screenshot-triggered"
            - "vr-event-image-failed"
            - "vr-event-dashboard-overlay-created"
            - "vr-event-switch-gamepad-focus"
            - "vr-event-request-screenshot"
            - "vr-event-screenshot-taken"
            - "vr-event-screenshot-failed"
            - "vr-event-submit-screenshot-to-dashboard"
            - "vr-event-screenshot-progress-to-dashboard"
            - "vr-event-primary-dashboard-device-changed"
            - "vr-event-room-view-shown"
            - "vr-event-room-view-hidden"
            - "vr-event-show-ui"
            - "vr-event-show-dev-tools"
            - "vr-event-desktop-view-updating"
            - "vr-event-desktop-view-ready"
            - "vr-event-start-dashboard"
            - "vr-event-elevate-prism"
            - "vr-event-overlay-closed"
            - "vr-event-dashboard-thumb-changed"
            - "vr-event-desktop-might-be-visible"
            - "vr-event-desktop-might-be-hidden"
            - "vr-event-notification-shown"
            - "vr-event-notification-hidden"
            - "vr-event-notification-begin-interaction"
            - "vr-event-notification-destroyed"
            - "vr-event-quit"
            - "vr-event-process-quit"
            - "vr-event-quit-acknowledged"
            - "vr-event-driver-requested-quit"
            - "vr-event-restart-requested"
            - "vr-event-invalidate-swap-texture-sets"
            - "vr-event-chaperone-data-has-changed"
            - "vr-event-chaperone-universe-has-changed"
            - "vr-event-chaperone-temp-data-has-changed"
            - "vr-event-chaperone-settings-have-changed"
            - "vr-event-seated-zero-pose-reset"
            - "vr-event-chaperone-flush-cache"
            - "vr-event-chaperone-room-setup-starting"
            - "vr-event-chaperone-room-setup-finished"
            - "vr-event-standing-zero-pose-reset"
            - "vr-event-audio-settings-have-changed"
            - "vr-event-background-setting-has-changed"
            - "vr-event-camera-settings-have-changed"
            - "vr-event-reprojection-setting-has-changed"
            - "vr-event-model-skin-settings-have-changed"
            - "vr-event-environment-settings-have-changed"
            - "vr-event-power-settings-have-changed"
            - "vr-event-enable-home-app-settings-have-changed"
            - "vr-event-steam-vr-section-setting-changed"
            - "vr-event-lighthouse-section-setting-changed"
            - "vr-event-null-section-setting-changed"
            - "vr-event-user-interface-section-setting-changed"
            - "vr-event-notifications-section-setting-changed"
            - "vr-event-keyboard-section-setting-changed"
            - "vr-event-perf-section-setting-changed"
            - "vr-event-dashboard-section-setting-changed"
            - "vr-event-web-interface-section-setting-changed"
            - "vr-event-trackers-section-setting-changed"
            - "vr-event-last-known-section-setting-changed"
            - "vr-event-dismissed-warnings-section-setting-changed"
            - "vr-event-gpu-speed-section-setting-changed"
            - "vr-event-windows-mr-section-setting-changed"
            - "vr-event-other-section-setting-changed"
            - "vr-event-any-driver-settings-changed"
            - "vr-event-status-update"
            - "vr-event-web-interface-install-driver-completed"
            - "vr-event-mc-image-updated"
            - "vr-event-firmware-update-started"
            - "vr-event-firmware-update-finished"
            - "vr-event-keyboard-closed"
            - "vr-event-keyboard-char-input"
            - "vr-event-keyboard-done"
            - "vr-event-keyboard-opened-global"
            - "vr-event-keyboard-closed-global"
            - "vr-event-application-list-updated"
            - "vr-event-application-mime-type-load"
            - "vr-event-process-connected"
            - "vr-event-process-disconnected"
            - "vr-event-compositor-chaperone-bounds-shown"
            - "vr-event-compositor-chaperone-bounds-hidden"
            - "vr-event-compositor-display-disconnected"
            - "vr-event-compositor-display-reconnected"
            - "vr-event-compositor-hdcp-error"
            - "vr-event-compositor-application-not-responding"
            - "vr-event-compositor-application-resumed"
            - "vr-event-compositor-out-of-video-memory"
            - "vr-event-compositor-display-mode-not-supported"
            - "vr-event-compositor-stage-override-ready"
            - "vr-event-compositor-request-disconnect-reconnect"
            - "vr-event-tracked-camera-start-video-stream"
            - "vr-event-tracked-camera-stop-video-stream"
            - "vr-event-tracked-camera-pause-video-stream"
            - "vr-event-tracked-camera-resume-video-stream"
            - "vr-event-tracked-camera-editing-surface"
            - "vr-event-performance-test-enable-capture"
            - "vr-event-performance-test-disable-capture"
            - "vr-event-performance-test-fidelity-level"
            - "vr-event-message-overlay-closed"
            - "vr-event-message-overlay-close-requested"
            - "vr-event-input-haptic-vibration"
            - "vr-event-input-binding-load-failed"
            - "vr-event-input-binding-load-successful"
            - "vr-event-input-action-manifest-reloaded"
            - "vr-event-input-action-manifest-load-failed"
            - "vr-event-input-progress-update"
            - "vr-event-input-tracker-activated"
            - "vr-event-input-bindings-updated"
            - "vr-event-input-binding-subscription-changed"
            - "vr-event-spatial-anchors-pose-updated"
            - "vr-event-spatial-anchors-descriptor-updated"
            - "vr-event-spatial-anchors-request-pose-update"
            - "vr-event-spatial-anchors-request-descriptor-update"
            - "vr-event-system-report-started"
            - "vr-event-monitor-show-headset-view"
            - "vr-event-monitor-hide-headset-view"
            - "vr-event-audio-set-speakers-volume"
            - "vr-event-audio-set-speakers-mute"
            - "vr-event-audio-set-microphone-volume"
            - "vr-event-audio-set-microphone-mute"
            - "vr-event-vendor-specific-reserved-start"
            - "vr-event-vendor-specific-reserved-end"
unregister_event:
  target:
    entity:
      integration: steamvr
      domain: binary_sensor
      device_class: running
  fields:
   event:
      required: true
      example: "vr-event-button-press"
      selector:
        select:
          translation_key: "event"
          options:
            - "vr-event-none"
            - "vr-event-tracked-device-activated"
            - "vr-event-tracked-device-deactivated"
            - "vr-event-tracked-device-updated"
            - "vr-event-tracked-device-user-interaction-started"
            - "vr-event-tracked-device-user-interaction-ended"
            - "vr-event-ipd-changed"
            - "vr-event-enter-standby-mode"
            - "vr-event-leave-standby-mode"
            - "vr-event-tracked-device-role-changed"
            - "vr-event-watchdog-wake-up-requested"
            - "vr-event-lens-distortion-changed"
            - "vr-event-property-changed"
            - "vr-event-wireless-disconnect"
            - "vr-event-wireless-reconnect"
            - "vr-event-reserved-01"
            - "vr-event-reserved-02"
            - "vr-event-button-press"
            - "vr-event-button-unpress"
            - "vr-event-button-touch"
            - "vr-event-button-untouch"
            - "vr-event-modal-cancel"
            - "vr-event-mouse-move"
            - "vr-event-mouse-button-down"
            - "vr-event-mouse-button-up"
            - "vr-event-focus-enter"
            - "vr-event-focus-leave"
            - "vr-event-scroll-discrete"
            - "vr-event-touch-pad-move"
            - "vr-event-overlay-focus-changed"
            - "vr-event-reload-overlays"
            - "vr-event-scroll-smooth"
            - "vr-event-lock-mouse-position"
            - "vr-event-unlock-mouse-position"
            - "vr-event-input-focus-captured"
            - "vr-event-input-focus-released"
            - "vr-event-scene-application-changed"
            - "vr-event-input-focus-changed"
            - "vr-event-scene-application-using-wrong-graphics-adapter"
            - "vr-event-action-binding-reloaded"
            - "vr-event-hide-render-models"
            - "vr-event-show-render-models"
            - "vr-event-scene-application-state-changed"
            - "vr-event-scene-app-pipe-disconnected"
            - "vr-event-console-opened"
            - "vr-event-console-closed"
            - "vr-event-overlay-shown"
            - "vr-event-overlay-hidden"
            - "vr-event-dashboard-activated"
            - "vr-event-dashboard-deactivated"
            - "vr-event-dashboard-requested"
            - "vr-event-reset-dashboard"
            - "vr-event-image-loaded"
            - "vr-event-show-keyboard"
            - "vr-event-hide-keyboard"
            - "vr-event-overlay-gamepad-focus-gained"
            - "vr-event-overlay-gamepad-focus-lost"
            - "vr-event-overlay-shared-texture-changed"
            - "vr-event-screenshot-triggered"
            - "vr-event-image-failed"
            - "vr-event-dashboard-overlay-created"
            - "vr-event-switch-gamepad-focus"
            - "vr-event-request-screenshot"
            - "vr-event-screenshot-taken"
            - "vr-event-screenshot-failed"
            - "vr-event-submit-screenshot-to-dashboard"
            - "vr-event-screenshot-progress-to-dashboard"
            - "vr-event-primary-dashboard-device-changed"
            - "vr-event-room-view-shown"
            - "vr-event-room-view-hidden"
            - "vr-event-show-ui"
            - "vr-event-show-dev-tools"
            - "vr-event-desktop-view-updating"
            - "vr-event-desktop-view-ready"
            - "vr-event-start-dashboard"
            - "vr-event-elevate-prism"
            - "vr-event-overlay-closed"
            - "vr-event-dashboard-thumb-changed"
            - "vr-event-desktop-might-be-visible"
            - "vr-event-desktop-might-be-hidden"
            - "vr-event-notification-shown"
            - "vr-event-notification-hidden"
            - "vr-event-notification-begin-interaction"
            - "vr-event-notification-destroyed"
            - "vr-event-quit"
            - "vr-event-process-quit"
            - "vr-event-quit-acknowledged"
            - "vr-event-driver-requested-quit"
            - "vr-event-restart-requested"
            - "vr-event-invalidate-swap-texture-sets"
            - "vr-event-chaperone-data-has-changed"
            - "vr-event-chaperone-universe-has-changed"
            - "vr-event-chaperone-temp-data-has-changed"
            - "vr-event-chaperone-settings-have-changed"
            - "vr-event-seated-zero-pose-reset"
            - "vr-event-chaperone-flush-cache"
            - "vr-event-chaperone-room-setup-starting"
            - "vr-event-chaperone-room-setup-finished"
            - "vr-event-standing-zero-pose-reset"
            - "vr-event-audio-settings-have-changed"
            - "vr-event-background-setting-has-changed"
            - "vr-event-camera-settings-have-changed"
            - "vr-event-reprojection-setting-has-changed"
            - "vr-event-model-skin-settings-have-changed"
            - "vr-event-environment-settings-have-changed"
            - "vr-event-power-settings-have-changed"
            - "vr-event-enable-home-app-settings-have-changed"
            - "vr-event-steamvr-section-setting-changed"
            - "vr-event-lighthouse-section-setting-changed"
            - "vr-event-null-section-setting-changed"
            - "vr-event-user-interface-section-setting-changed"
            - "vr-event-notifications-section-setting-changed"
            - "vr-event-keyboard-section-setting-changed"
            - "vr-event-perf-section-setting-changed"
            - "vr-event-dashboard-section-setting-changed"
            - "vr-event-web-interface-section-setting-changed"
            - "vr-event-trackers-section-setting-changed"
            - "vr-event-last-known-section-setting-changed"
            - "vr-event-dismissed-warnings-section-setting-changed"
            - "vr-event-gpu-speed-section-setting-changed"
            - "vr-event-windows-mr-section-setting-changed"
            - "vr-event-other-section-setting-changed"
            - "vr-event-any-driver-settings-changed"
            - "vr-event-status-update"
            - "vr-event-web-interface-install-driver-completed"
            - "vr-event-mc-image-updated"
            - "vr-event-firmware-update-started"
            - "vr-event-firmware-update-finished"
            - "vr-event-keyboard-closed"
            - "vr-event-keyboard-char-input"
            - "vr-event-keyboard-done"
            - "vr-event-keyboard-opened-global"
            - "vr-event-keyboard-closed-global"
            - "vr-event-application-list-updated"
            - "vr-event-application-mime-type-load"
            - "vr-event-process-connected"
            - "vr-event-process-disconnected"
            - "vr-event-compositor-chaperone-bounds-shown"
            - "vr-event-compositor-chaperone-bounds-hidden"
            - "vr-event-compositor-display-disconnected"
            - "vr-event-compositor-display-reconnected"
            - "vr-event-compositor-hdcp-error"
            - "vr-event-compositor-application-not-responding"
            - "vr-event-compositor-application-resumed"
            - "vr-event-compositor-out-of-video-memory"
            - "vr-event-compositor-display-mode-not-supported"
            - "vr-event-compositor-stage-override-ready"
            - "vr-event-compositor-request-disconnect-reconnect"
            - "vr-event-tracked-camera-start-video-stream"
            - "vr-event-tracked-camera-stop-video-stream"
            - "vr-event-tracked-camera-pause-video-stream"
            - "vr-event-tracked-camera-resume-video-stream"
            - "vr-event-tracked-camera-editing-surface"
            - "vr-event-performance-test-enable-capture"
            - "vr-event-performance-test-disable-capture"
            - "vr-event-performance-test-fidelity-level"
            - "vr-event-message-overlay-closed"
            - "vr-event-message-overlay-close-requested"
            - "vr-event-input-haptic-vibration"
            - "vr-event-input-binding-load-failed"
            - "vr-event-input-binding-load-successful"
            - "vr-event-input-action-manifest-reloaded"
            - "vr-event-input-action-manifest-load-failed"
            - "vr-event-input-progress-update"
            - "vr-event-input-tracker-activated"
            - "vr-event-input-bindings-updated"
            - "vr-event-input-binding-subscription-changed"
            - "vr-event-spatial-anchors-pose-updated"
            - "vr-event-spatial-anchors-descriptor-updated"
            - "vr-event-spatial-anchors-request-pose-update"
            - "vr-event-spatial-anchors-request-descriptor-update"
            - "vr-event-system-report-started"
            - "vr-event-monitor-show-headset-view"
            - "vr-event-monitor-hide-headset-view"
            - "vr-event-audio-set-speakers-volume"
            - "vr-event-audio-set-speakers-mute"
            - "vr-event-audio-set-microphone-volume"
            - "vr-event-audio-set-microphone-mute"
            - "vr-event-vendor-specific-reserved-start"
            - "vr-event-vendor-specific-reserved-end"